name: Build Gradle project

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build --info
      - name: Archive build reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: ${{ matrix.os }}-build-reports
          path: build/reports
          retention-days: 1
      - name: Archive build reports core
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: ${{ matrix.os }}-build-reports-core
          path: core/build/reports
          retention-days: 1
