name: Build Gradle project

on:
  push:

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build --info
      - name: Archive build reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: ubuntu-build-reports
          path: build/reports
          retention-days: 1
      - name: Archive build reports core
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: ubuntu-build-reports-core
          path: core/build/reports
          retention-days: 1
  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build --info
      - name: Archive build reports
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: windows-build-reports
          path: build/reports
          retention-days: 1
      - name: Archive build reports core
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: windows-build-reports-core
          path: core/build/reports
          retention-days: 1